In [2]:
import os
import json
import requests

import pandas as pd
import matplotlib.pyplot as plt
import datetime

from pprint import pprint
#from scrapy import Selector
from tqdm.notebook import tqdm

from functions import *

from sqlalchemy import create_engine
import mysql.connector

In [3]:
%load_ext autoreload 
%load_ext sql
%config SqlMagic.displaylimit = None
%config SqlMagic.autocommit=True

In [4]:
engine = create_engine('sqlite:///../data/states_reddit.db', echo=False, isolation_level="AUTOCOMMIT")

with engine.connect() as conn:
    pass

In [5]:

all_data = scrape_all_subreddits(subreddits)

t3_17forud
t3_17yzofb
t3_17f1v5r
t3_15uplzz
t3_16w7udb
t3_150gtt1
t3_12xwxbr
t3_16at6jj
t3_17n7xqc
t3_13w5ohz
t3_1597mld
t3_131vgcf
t3_16tyh3y
t3_1boq8by
t3_17kidzh
t3_15k25ju
t3_183p911
t3_14f7utx
t3_1avzsmj
t3_14zkw0f
t3_14jhknl
t3_14ss4ku
t3_1bgz075
t3_191l3lh
t3_18z391f
t3_18u5vh4
t3_1aluzqx
t3_13x80co
t3_1ae247t
t3_1belhd7
t3_14b0b55
t3_13vv3ll
t3_1919q2v
t3_17m7kjq
t3_17n3umf
t3_13orpjq
t3_13xkayc
t3_1bfdtkx
t3_1647w3a
t3_1922xtr
t3_1bt3cg5
t3_17d3qvx
t3_192vg9c
t3_15j0al4
t3_17apsmq
t3_13dnpdt
t3_14rsi65
t3_19edxk8
t3_154tsnn
t3_15ecppp
t3_13d2ygu
t3_12f5tek
t3_1bdrnj4
t3_19e38xg
t3_184uvg1
t3_16s7nnr
t3_19ankr9
t3_1aefhpn
t3_15ydrow
t3_1913xrm
t3_143lnjo
t3_14pwlm3
t3_1ae0txb
t3_1bcylu2
t3_14eo3kx
t3_198upy2
t3_18tb0ok
t3_18musrx
t3_18a06fm
t3_12z1v25
t3_17p1gqq
t3_1bfuj5o
t3_17fgz05
t3_1ap2jfl
t3_166ve33
t3_18xppyg
t3_14tim13
t3_13eydkw
t3_140g8ys
t3_12fq3re
t3_13xz7on
t3_15yawxt
t3_1b936ns
t3_1ahcavj
t3_16q6e98
t3_17wmrp9
t3_14fh72b
t3_144gk79
t3_15y21aa
t3_17986d7
t3_16pdy5l
t3_17ht2sp
t3_1963pbd
t3_13k2ok3
t3_12pls7x
t3_1aqcyc3
t3_1390gkv
t3_1bn3v1i
t3_162tr82
t3_15bwcud
t3_17m2khz
t3_13l6y04
t3_13orcg2
t3_1ad7cqi
t3_1aflx0f
t3_14232s1
t3_1ady767
t3_147mwuq
t3_1594hwy
t3_17h1415
t3_19bq11i
t3_1340xxx
t3_14ww4pr
t3_16t6wz1
t3_13q0kn7
t3_189ve8t
t3_130iihi
t3_1agslz0
t3_13nqoqk
t3_12s615c
t3_18jz7il
t3_194v087
t3_1bmvzll
t3_15i31vu
t3_1b6k601
t3_16zaka8
t3_1anuklb
t3_13j3ryt
t3_1b1b5id
t3_1bst31i
t3_12xn13p
t3_177ban1
t3_1atules
t3_12zydcy
t3_14av67s
t3_1bl4akl
t3_137qnlg
t3_12zg5a1
t3_14adrrr
t3_1aqam15
t3_16s9ooc
t3_16bo6xe
t3_15uvtku
t3_15zmveh
t3_1b3kafo
t3_16e7peo
t3_1awjwap
t3_171f86o
t3_150qh0f
t3_16744fx
t3_1be4ca0
t3_16yeu4i
t3_17fj18n
t3_16ko81i
t3_14vm7hw
t3_14bwgzv
t3_18nmng6
t3_143wcub
t3_12uh6ff
t3_19dwvav
t3_13dtzn8
t3_196tssu
t3_13bdeoy
t3_1bfjdnt
t3_18kxija
t3_16b0tk5
t3_1557rs3
t3_13lzzi2
t3_1aqt1t5
t3_14b6n76
t3_1985vjs
t3_136j7ie
t3_12m06zm
t3_1aqanll
t3_18yj1vx
t3_1413twe
t3_1apduzs
t3_131vbyv
t3_17yk3g6
t3_15y02sh
t3_1ap6jbr
t3_1an0952
t3_17sca0b
t3_15qk1u0
t3_16z9yl0
t3_17eyf5v
t3_17n796b
t3_198yxvm
t3_18y23iv
t3_1aepei9
t3_13k8ytu
t3_13tns3n
t3_14c9gb9
t3_16889iy
t3_15whjmc
t3_171tqkd
t3_13g45kc
t3_15nw1zy
t3_18vaab0
t3_13ncpi1
t3_19di551
t3_162sl77
t3_14y90gl
t3_1362vf7
t3_152l7id
t3_12kr5iz
t3_13tra87
t3_12xks69
t3_13g3iol
t3_15nyi2d
t3_1bjrqet
t3_153cdtq
t3_177tkzp
t3_17b5lpu
t3_16ed18s
t3_17cgmky
t3_13g4uax
t3_1486rdk
t3_17cciu4
t3_18tynvu
t3_196lmt7
t3_15cdqp7
t3_12iqn0z
t3_19a5xsp
t3_1bmpy8t
t3_16ayaqb
t3_1acpxd9
t3_15u4rdx
t3_16z9zm5
t3_1asbjhh
t3_1bhvpr7
t3_1b881co
t3_17t19ag
t3_19bgddt
t3_140hhm7
t3_144b40z
t3_158c58v
t3_12vsb0k
t3_18tr18s
t3_17d5xyj
t3_15aki8h
t3_132gic1
t3_190gnft
t3_1962hpv
t3_1b3f0mt
t3_12xs56b
t3_159oyxi
t3_19dj2jx
t3_1b1raz3
t3_14rorf8
t3_1aqflps
t3_16qmcrd
t3_13zwino
t3_1b2zfl2
t3_14i5vvw
t3_12jtlv3
t3_12ol5y4
t3_12riwnr
t3_1948h2k
t3_15r096p
t3_17ileor
t3_18md1vq
t3_18vixor
t3_1473u0k
t3_16xixfl
t3_12e7bfx
t3_13b52oa
t3_1avfjk3
t3_13ucjym
t3_13k2s0b

In [6]:
all_data.to_sql('states_data', engine, if_exists='replace', index=False)

27000

In [7]:
state_data = pd.read_sql('SELECT * FROM states_data', engine)

state_data.head()

,subreddit,title,selftext,created_utc,id,upvote_ratio,ups,num_comments
0,newyork,Democrats overtake Monroe County Legislature f...,,1.699458e+09,17qoenc,0.96,1989,90
1,newyork,New York man who fatally shot woman after her ...,,1.709309e+09,1b3xn3i,0.99,1762,153
2,newyork,New Yorkers can now buy booze on Sunday mornings,,1.697490e+09,179goe7,0.98,1342,102
3,newyork,Democrats secure a supermajority of seats on B...,,1.699738e+09,17t47v6,0.94,1087,85
4,newyork,Former Olympian Caitlyn Jenner backs New York ...,,1.710798e+09,1bi2zlx,0.94,997,300

In [8]:
all_data

,subreddit,title,selftext,created_utc,id,upvote_ratio,ups,num_comments
0,newyork,Democrats overtake Monroe County Legislature f...,,1.699458e+09,17qoenc,0.96,1989,90
1,newyork,New York man who fatally shot woman after her ...,,1.709309e+09,1b3xn3i,0.99,1762,153
2,newyork,New Yorkers can now buy booze on Sunday mornings,,1.697490e+09,179goe7,0.98,1342,102
3,newyork,Democrats secure a supermajority of seats on B...,,1.699738e+09,17t47v6,0.94,1087,85
4,newyork,Former Olympian Caitlyn Jenner backs New York ...,,1.710798e+09,1bi2zlx,0.94,997,300
...,...,...,...,...,...,...,...,...
26995,politics,Trump loses to Biden by six points in new poll,,1.706731e+09,1afr5la,0.84,22398,3394
26996,politics,Trump’s dogwhistle to the Christian right is a...,,1.684147e+09,13i4bme,0.89,22377,1646
26997,politics,Trump loses bid to delay $83.3 million E. Jean...,,1.709850e+09,1b97d7q,0.95,22366,1443
26998,politics,Trump Gives Away the Game With January 6 Confe...,,1.700246e+09,17xlj3e,0.94,22355,1054
26999,politics,Biden takes tougher work requirements for welf...,,1.684332e+09,13k2s0b,0.94,22322,1562